### ISSUE TITLE
env: ruby18: No such file or directory

### ISSUE THREAD

**Issue by willfaught** [syscrusher/golang.tmbundle#26]
When I format Go code, I get this error:

    Failure running “Imports”.

    env: ruby18: No such file or directory

Can't the code just specify `ruby`? Why the dependency on 1.8?

**Comment by infininight** [comment]
Some bundle support libraries and commands still require 1.8 of ruby so we include a version in TextMate solely for it's use. There can be two causes for the error:

- You have disabled the Bundle Support bundle, check in Preferences to make sure you have the following bundles checked as they are important support bundles: Bundle Support, Text, Source, TextMate, SCM
- You have set an explicit `PATH` variable value in preferences, this should be done by extending the path. See [this blog post](http://blog.macromates.com/2014/defining-a-path/) for more information.

\- Michael Sheets, MacroMates Support

**Comment by syscrusher** [comment]
Pretty much all of the Ruby within the bundle was written assuming 1.8, so using TM's built-in copy was the easy way to handle it.

After reviewing and testing everything seems fine, so I've removed the version specification from most of the bundle. The 'Open Package' command still has issues, so it will still depend on 1.8. I haven't worked with 1.8 -> 1.9+ compatibility issues, and instead of fixing that I'd rather potentially replace it with a more useful implementation.
