### ISSUE TITLE
Preference-Variables not working...

### ISSUE THREAD

**Issue by xgz123** [syscrusher/golang.tmbundle#40]
It just keep show me Unable to run “Fmt”. 
I have add those variables to the settings. And add those to the system env file then run `mate some.go`, still not working.

macOS sierra

textmate2

**Comment by infininight** [comment]
You are getting an error about not finding the `gofmt` command? If it is in any of the following locations it shouldn't even be necessary to setup the variable:

- `/opt/local/bin/gofmt`
- `/usr/local/bin/gofmt`
- `/usr/local/go/bin/gofmt`

Please give an exact list of steps performed and the result expected vs what happens.

**Comment by xgz123** [comment]
Hi, @infininight here is my setting:
https://drive.google.com/open?id=0Bz0MK78BvgY1ZnFuT2hzVFhNRXc

and the error

https://drive.google.com/open?id=0Bz0MK78BvgY1enpxaGVHbEhLSUE

and the env

https://drive.google.com/open?id=0Bz0MK78BvgY1NS1PbXZxbGlORWc

and Bundles-Go-run

https://drive.google.com/open?id=0Bz0MK78BvgY1SFdNclhjX2tnSHM

Thanks!

**Comment by infininight** [comment]
OK, based on the final image it seems that go is being run successfully by TextMate. The error then would be not with defining the path inside TextMate but some setting requirement internal to go. It would seem it is looking for `GOROOT` in the wrong location, but would need someone familiar with go to answer that. I would have expected go to set `GOROOT` itself but you could try setting it yourself in settings?

It would be weird though as I have go installed through Homebrew and it works fine without setting any settings at all. (Since it's in a location that TextMate expects by default.)

**Comment by xgz123** [comment]
It seems like the editor didn't read the setting at all.But when set TM_GOFMT to goimports, it works.
Really weird.
One thing I'm sure about is that `GOPATH` and `GOROOT`  is correct.

**Comment by infininight** [comment]
TextMate does not source any bash/etc startup files, so the only variables that are set are the ones in preferences. So `GOROOT` would be the default.

**Comment by xgz123** [comment]
> TextMate does not inherit the users environment unless it is launched from the command line.
@infininight it can read env.I tried and failed.

**Comment by syscrusher** [comment]
I think you may be experiencing 2 separate issues.

First is that TextMate can't find gofmt. You mentioned that it works when you set TM_GOFMT to point to goimports. Can you confirm that gofmt exists at `~/app/go/bin/gofmt`? Does it work if you manually call it on a go file? Do you have issues with running lint?
If TextMate is properly calling goimports when you set the variable, it should be able to properly call gofmt. The gofmt command in TextMate is powered by a simple bash expression: `(eval "${TM_GOFMT:-gofmt}")`. If TM_GOFMT is set, call that, otherwise call gofmt generically. gofmt should work independently of having GOROOT set, but I may be wrong.

Second is finding GOROOT. How did you install go? The go utility embeds GOROOT internally because it is just a frontend. It has to find the correct compiler within GOROOT to actually do work. If the embedded GOROOT doesn't match the actual location of GOROOT, then you have to set the environment variable. We don't handle TM_GOROOT specifically, but you should be able to make it work by setting plain GOROOT inside of TextMate.

If none of that works, can you post the output of `go env`?

**Comment by xgz123** [comment]
@syscrusher Thanks!
`~/app/go/bin/gofmt` this path is correct and it can work.

Second, after I set GOROOT inside TextMate, everything works fine now.
Thanks for your work.
